### ISSUE TITLE
How to create parabolic motion with "animate" function

### ISSUE THREAD

**Issue by Arti3DPlayer** [koggdal/ocanvas#104]
Can i do this ?

**Comment by koggdal** [comment]
I think the easiest would be to not use `animate` if you're after real parabolic motion with real forces. The animation easing functions in oCanvas work by calculating a position in the animation that can be applied to any property. You could set up two animations (one for X movement and one for Y movement), but it's only easy to do if moving in the same direction all the time. I made [a demo](http://ocanvas.org/testcases/animate-parabolic/) for that. But if you want a motion where the object moves up and then down again, it's probably more tricky to do with `animate`, as it applies the property position on the diff between start and end value, and if you want to move up and then down again, start and end value could be the same.
