### ISSUE TITLE
how can draw a pencil/brush liked line?

### ISSUE THREAD

**Issue by iceman-fx** [koggdal/ocanvas#106]
Hi,
how can i draw a line (multiple points) along my mouse trail - like the photoshop pencil/brush tool ?

**Comment by koggdal** [comment]
Hi,

Are you looking for making brush strokes that turn into movable objects when releasing? Or just drawing? If you just want to draw, I'd say that oCanvas is probably not the best option. The purpose of this library is to help with objects on the screen. You're probably better off doing it manually via the regular canvas API.

But, if you're looking to turn the strokes into objects when released, I would probably go for making the drawing itself manually just like above, but on a separate canvas element. Then when you release, copy the canvas contents over into another canvas or as a data URI. That canvas can then be used to draw a [custom object](http://ocanvas.org/docs/oCanvas-Object/registerDisplayObject) via [drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage).

For the draw logic itself, there's probably lots of information online on how to do that, but you could have a look at a project I made a few years ago (**not** with oCanvas). A drawing application with canvas (works just as well in a desktop browser as on the phone, just click Try it now).

http://drawpad.net/
https://github.com/koggdal/drawpad
https://github.com/koggdal/drawpad/blob/master/js/draw.js
