### ISSUE TITLE
how

### ISSUE THREAD

**Issue by shortbaby** [koggdal/ocanvas#117]

**Comment by shortbaby** [comment]
i didn't realize how does the quene worked  , i want some demo show me。ok？plz。

**Comment by koggdal** [comment]
I'm sorry, but how does what work?

**Comment by shortbaby** [comment]
in the animation’s , i don't kown how to use the 'quene' in options args.  i don't understand ,  the documentation's description didn't give a demo .  i want to learn the source code,so  i want you give me some help

**Comment by koggdal** [comment]
Oh the animation queues! I created two more examples now in the animation docs, hopefully that should clear it up for you :smiley: 

Without queues:
http://ocanvas.org/docs/Animation/animate#example-2

With queues:
http://ocanvas.org/docs/Animation/animate#example-3
