### ISSUE TITLE
Provide NPM package

### ISSUE THREAD

**Issue by legomind** [koggdal/ocanvas#121]
An NPM package would make life a little easier for those of us using webpack or browserify.

**Comment by koggdal** [comment]
Spent some time today to set that up, so all done now! :smiley: 

```
npm install --save ocanvas
```

```js
var oCanvas = require('ocanvas');

var canvas = oCanvas.create({
  canvas: '#canvas',
  background: '#222'
});
```

There's currently only a single entry point, and modules from oCanvas should not be required directly, they should be accessed from the `oCanvas` object just like before. Future versions will most likely expose things differently.

**Comment by legomind** [comment]
Woot! Thanks!
