### ISSUE TITLE
Adding child element to parent, how do you make it show behind the parent?

### ISSUE THREAD

**Issue by labago** [koggdal/ocanvas#123]
```
var torso = canvas.display.image(avatar.torso);
	var head = canvas.display.image(avatar.head);
	var hair = canvas.display.image(avatar.hair);
	var leftArm = canvas.display.image(avatar.leftArm);
	canvas.addChild(torso);
	torso.addChild(head);
	torso.addChild(leftArm);
	leftArm.zIndex = 0;
	canvas.redraw();
```

According to the documentation this should position leftArm behind torso, however it still shows the left arm in front of the torso.

**Comment by labago** [comment]
Also, I know I can accomplish this by adding both to the canvas object, but I would like to retain the positional relationship of the torso to the left arm if possible, just need to position the left arm behind its parent object on the canvas

**Comment by koggdal** [comment]
The `zIndex` property is the index of the object in the list of children for a certain object. Higher index means closer to the viewer. However, there is no relation here to the object itself, only to the other children. So setting `zIndex` of `leftArm` to `0` will put it behind `head`, but all children are still rendered on top of the object itself (`torso`). If you want to keep the grouping for position etc, you can create an invisible object just for the grouping:

```
var body = canvas.display.rectangle({});
body.addChild(head);
body.addChild(torso);
body.addChild(leftArm);
```

The `body` object will not get any size based on the children, so if you want the object to have a more sensible size than the default zero you can set `width` and `height` manually. It won't make any difference though, mostly if you want to make things easy for you later when you move the body around and need the size for any calculation.

**Comment by labago** [comment]
Thanks! Makes sense
