### ISSUE TITLE
core not finding canvas

### ISSUE THREAD

**Issue by QuinDennis** [koggdal/ocanvas#127]
I had to modify this code to find the canvas element:
			// Set canvas to the element specified using a selector
			else if (typeof this.settings.canvas === "string") {
				this.canvasElement = document.querySelector(this.settings.canvas);
			}
			if (this.canvasElement == undefined) 
				this.canvasElement = document.getElementById(this.settings.canvas)
			
document.querySelector didn't work.

Is this library still active and supported/

**Comment by koggdal** [comment]
The `canvas` property should have either a CSS selector as a value, or a reference to the DOM node. So, if you have a canvas element with an ID `my-canvas`, you will specify `canvas: '#my-canvas'`, since that is the syntax to target an ID with a CSS selector.

The library is not actively developed with new features, but I try to respond to and fix issues as quickly as I can.

**Comment by QuinDennis** [comment]
with '#' is does find the canvas, but then canvas.display.ellipse is not defined.  are some things loading asynchronously?

<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="js/ocanvas-2.8.4.js"></script>
<script type="text/javascript" src="js/index.js"></script>
</script>
</head>
<body>
	<canvas id="myCanvas"></canvas>
</body>
</html> 

// index.js
var canvas, center
function init() { 
    canvas = oCanvas.create({
	    canvas: "#myCanvas",
	    background: "#222",
	    fps: 60
    });

    // Center planet
    center = canvas.display.ellipse({
	    x: canvas.width / 2, y: canvas.height / 2,
	    radius: canvas.width / 20,
	    fill: "#fff"
    }).add();
}
window.onload = init

**Comment by koggdal** [comment]
Assigning to `window.onload` sets up an event listener for the load event of the document. You only run `init` when that happens, but since that is async, the other code that creates the planet runs first, and then `init` is run. So you need to delay everything until `init` runs.

**Comment by koggdal** [comment]
Okay, maybe it was hard seeing the indentation in that broken code block. So all of that is already in the `init` function? Then that should work. Could you create a jsfiddle or something with a test case maybe?

**Comment by QuinDennis** [comment]
I'm not really familiar with jsfiddle, but here goes.  
https://jsfiddle.net/a80zaq7o/1/#&togetherjs=CJwhHoxinj

**Comment by koggdal** [comment]
Okay, so you only need `#` when it's a CSS selector. The `id` attribute on the canvas element should not have that character, since it's not specifying a CSS selector, so that should be: `<canvas id="myCanvas"></canvas>`. And then `canvas: "#myCanvas",` in the call to `oCanvas.create`.
