### ISSUE TITLE
Draw curve line 

### ISSUE THREAD

**Issue by Krimik** [koggdal/ocanvas#132]
Hi.

Is it possible to draw a curved line (random particle path) without drawing a lot of rectangle objects? If I draw a lot of 1 pixel squares, memory gets filled very quickly, but I feel there must be a way to just draw a  freeshape curved line and treat it is one object?

Thanks

**Comment by koggdal** [comment]
You can use this API to create a custom display object where you have access to the native canvas API, which lets you draw paths: http://ocanvas.org/docs/Display-Objects/register
