### ISSUE TITLE
animate(xxx, callback ), callback be called when the animation has finished

### ISSUE THREAD

**Issue by fdandan** [koggdal/ocanvas#133]
i see the api document, animate(props [, duration [, easing [, newQueue [, callback ]]]]), but the callback  will be called when the animation has finished , i want to get every frame, so i hope the callback will be called when frame change, , not supported ? or how i can do?   thanks~

**Comment by koggdal** [comment]
No, sorry, there's no hook for that. However, you could use `window.requestAnimationFrame` to get a callback for the next frame.
