### ISSUE TITLE
init method for custom display objects

### ISSUE THREAD

**Issue by jmlop** [koggdal/ocanvas#135]
I am not the best programmer and new in javascript and all this.
I am trying to use custom display objects and the init function does not work. I think the error is in
			if (init !== undefined && typeof display[name][init] === "function") {
I've changed by
			if (init !== undefined && typeof retObj[init] === "function") {
I am doing something wrong

**Comment by koggdal** [comment]
Thanks for reporting! The fix will go out in a bit with version 2.8.7.

**Comment by koggdal** [comment]
2.8.7 is here: http://ocanvas.org/download#v2.8.7

**Comment by jmlop** [comment]
Thanks, now works perfectly.
