### ISSUE TITLE
oCanvas not working due to TypeError

### ISSUE THREAD

**Issue by mount2010** [koggdal/ocanvas#136]
When trying to run oCanvas, the following errors pop up in the console:
(Firefox 52 on Ubuntu)
TypeError: this.canvasElement is null
(Google Chrome on Ubuntu)
Uncaught TypeError: Cannot read property 'getContext' of null

The following code was run:
HTML
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>oCanvas Test</title>
</head>
<body>

</body>
<script src="ocanvas-2.8.7.min.js"></script>
<script src="untitled.js"></script>
</html>
```
JS
```
const canvas = oCanvas.create({
	canvas: "#canvas",
	background:"#000",
	fps:60
});
```
.

**Comment by koggdal** [comment]
You need to create the canvas element yourself. The `canvas` property in the options object passed to `oCanvas.create` can be a CSS selector referencing a canvas element you already have in the DOM, or you can provide the DOM node directly.

You can choose one of these options:

**Option 1**
Add canvas element to the HTML (with an ID of `canvas` as you're referencing `#canvas` in the JS):

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>oCanvas Test</title>
</head>
<body>
  <canvas id="canvas" width="800" height="600"></canvas>
</body>
<script src="ocanvas-2.8.7.min.js"></script>
<script src="untitled.js"></script>
</html>
```

**Option 2**
Create the canvas element in JS:

```js
const canvas = oCanvas.create({
  canvas: document.createElement('canvas'),
  background:"#000",
  fps:60
});
```

**Docs**
http://ocanvas.org/docs/oCanvas-Object/create
