### ISSUE TITLE
getOrigin method for ellipse widget calculates wrong values

### ISSUE THREAD

**Issue by lionstorke** [koggdal/ocanvas#141]
When using ellipse widget,, getOrigin() method returns -this.radius for origin.x === "left". The same applies for orgin.y when origin.y === "top". If you put that ellipse widget on a rectangle with the dimension width = 2 * radius_x and height = 2 * radius_y, and resize both widgets, the ellipse widget will be drawn outside the rectangle. See the attached image
![grafik](https://user-images.githubusercontent.com/29922835/27869579-a3a3c72e-61a0-11e7-9121-1f5bb142734b.png)

If I use radius_x and radius_y for the calculation, ellipse drawing works as expected.

Original code (ocanvas.js 2.8.4)
// Method for getting the current origin coordinates in pixels
getOrigin: function () {
	var x, y,
		origin = this.origin,
		shapeType = this.shapeType;
	
	// Get X coordinate in pixels
	if (origin.x === "center") {
		x = (shapeType === "rectangular") ? this.width / 2 : 0;
	} else if (origin.x === "right") {
		x = (shapeType === "rectangular") ? this.width : this.radius;
	} else if (origin.x === "left") {
		x = (shapeType === "rectangular") ? 0 : -this.radius;
	} else {
		x = !isNaN(parseFloat(origin.x)) ? parseFloat(origin.x) : 0;
	}
	
	// Get Y coordinate in pixels
	if (origin.y === "center") {
		y = (shapeType === "rectangular") ? this.height / 2 : 0;
	} else if (origin.y === "bottom") {
		y = (shapeType === "rectangular") ? this.height : this.radius;
	} else if (origin.y === "top") {
		y = (shapeType === "rectangular") ? 0 : -this.radius;
	} else {
		y = !isNaN(parseFloat(origin.y)) ? parseFloat(origin.y) : 0;
	}
	
	// Return pixel coordinates
	return {
		x: x,
		y: y
	};
},

Fixed code 👍 // Method for getting the current origin coordinates in pixels
getOrigin: function () {
	var x, y,
		origin = this.origin,
		shapeType = this.shapeType;
	
	// Get X coordinate in pixels
	// Bug, modified this.radius to this.radius_x
	if (origin.x === "center") {
		x = (shapeType === "rectangular") ? this.width / 2 : 0;
	} else if (origin.x === "right") {
		x = (shapeType === "rectangular") ? this.width : this.radius_x;
	} else if (origin.x === "left") {
		x = (shapeType === "rectangular") ? 0 : -this.radius_x;
	} else {
		x = !isNaN(parseFloat(origin.x)) ? parseFloat(origin.x) : 0;
	}
	
	// Get Y coordinate in pixels
	// Bug, modified this.radius to this.radius_y
	if (origin.y === "center") {
		y = (shapeType === "rectangular") ? this.height / 2 : 0;
	} else if (origin.y === "bottom") {
		y = (shapeType === "rectangular") ? this.height : this.radius_y;
	} else if (origin.y === "top") {
		y = (shapeType === "rectangular") ? 0 : -this.radius_y;
	} else {
		y = !isNaN(parseFloat(origin.y)) ? parseFloat(origin.y) : 0;
	}
	
	// Return pixel coordinates
	return {
		x: x,
		y: y
	};
},

**Comment by koggdal** [comment]
Thanks for reporting! This is now fixed in 2.8.9: http://ocanvas.org/download#v2.8.9

**Comment by lionstorke** [comment]
Thanks for the quick fix. It’s working as expected.
