### ISSUE TITLE
Ellipse widget: mouse events at wrong position, when ellipse origin is "left", "top"

### ISSUE THREAD

**Issue by lionstorke** [koggdal/ocanvas#143]
I have an ellipse widget and use it with setOrigin("left", "top"); See code:

var widget = this.ocanvas.display.ellipse({
	x: 226,
	y: 167,
	radius_x: 34.5,
	radius_y: 76.5,
	fill: "transparent"
});
widget.setOrigin("left", "top"); // Mouse position at wrong position
//widget.setOrigin("center", "center"); // Mouse position correct
widget.stroke = "outside 3px rgba(250, 0, 0, 1)";
widget.fill = "yellow";
widget.bind("mousemove", function(){
	var mp = my.createMousePoint();  // Creates a mouse point from this.ocanvas.pointer.x and this.ocanvas.pointer.y
	console.info("Elypse: this.widget: mousemove: mp: " + mp);
	my.triggerEventTooltipChanged("Elypse: this.widget: mousemove: mp: " + mp); // Displays the tooltip
});

In this case, mouse events are fired outside the ellipse widget. See attached image.
![ellipse-mousemove-left-top](https://user-images.githubusercontent.com/29922835/27910081-dea1e08c-6253-11e7-8a21-779496bd3622.png)

Tooltip for ellipse widget is outside yellow ellipse.

If I use setOrigin("center", "center") (commented in code above) everything is fine. See attached second image.
![ellipse-mousemove-center-center](https://user-images.githubusercontent.com/29922835/27910289-c629bfec-6254-11e7-83a4-b52816e0c7c3.png)

**Comment by koggdal** [comment]
Thanks for this report as well! :) Fixed now in 2.8.10: http://ocanvas.org/download#v2.8.10

**Comment by lionstorke** [comment]
Thank you very much for the quick fix. Works well and as expected.
