### ISSUE TITLE
zIndex is not work

### ISSUE THREAD

**Issue by linghao2014** [koggdal/ocanvas#149]
zIndex is not the value that I set it but the order I add to canvas.

**Comment by koggdal** [comment]
Can you please provide some sample code that illustrates your problem? Thanks.

**Comment by linghao2014** [comment]
`//Obj1 zIndex=100
let canvArr = [Obj1,Obj2,Obj3];
for(let para of canvArr){
	canvas.addChild(para);
}
//Obj4 zIndex=1
canvas.addChild(Obj4);`

I use the image Objects. The last Obj1's zIndex is 0 and Obj4's zIndex is 3 .
zIndex has been covered?

**Comment by koggdal** [comment]
Ahh then I get it. You must set the `zIndex` property after adding the objects. This is documented here: http://ocanvas.org/docs/Display-Objects/Base#property-zIndex
